### ISSUE TITLE
Question about not including pandas

### ISSUE THREAD

**Issue by jfreedman0** [orikami-nl/sklearn-build#1]
Was pandas not included because it caused the zip to be too large for AWS Lambda? I've followed the blogpost and am running into an issue with my venv.zip file being 55MB which is too large to upload to Lambda. Any suggestions for getting numpy, scipy, AND pandas all on lambda together?

**Comment by philippatterson** [comment]
Just an FYI ... it is not the compressed size of the ZIP file that matters, it is the size after it is uncompressed.  The limitation from AWS is that it must be under 250MB uncompressed.   Without striping the debug symbols and deleting all of the unnecessary "stuff" (like documentation), Numpy, Pandas and SciKit-learn will be more than 1GB after they are uncompressed.

If the uncompressed size is under the 250MB limit but you are having issues with deploying the 55MB zip, it requires deploying from an S3 bucket instead of directly to Lambda.  This is what Serverless and other tools (like SAM, ...) do.

**Comment by jfreedman0** [comment]
That's good to know. Thank you. I was under the impression after reading the blog post (https://blog.orikami.nl/building-scipy-pandas-and-numpy-for-aws-lambda-python-3-6-cba9355b44e9) that I should end up with a zip file that I can upload to Lambda directly. Is that not correct?

**Comment by philippatterson** [comment]
It does look like and imply that you should be able to, but it looks a lot more like this was only really tested using Docker.  Maybe the authors of this repo can comment.  They do specify that they excluded Pandas intentionally, so it may just be too large with it.   If you are try to create and deploy a Lambda directly from the AWS CLI or web console, you will have a lot of problems.
I highly recommend using one of the frameworks like Serverless or SAM to do this.  also make sure you have CloudWatch logs enabled, you will find the error message in there if the Zip is too large.
Here is another repo that does it for Python 2.7 https://github.com/ryfeus/lambda-packs maybe it will provide some better guidance or other ideas.

**Comment by stekaiser** [comment]
@jfreedman0 You have to first upload the zip file to a S3 bucket and then use the option 'Upload a file from Amazon S3'. This will enable you to use the zip file with numpy, pandas and scipy.

**Comment by jfreedman0** [comment]
Thanks for all the help! Ended up following the blog post to add all my dependencies and handler to a zip file and used the Serverless framework with the following added to my serverless config:

```yaml
package:
  artifact: path/to/zip
```
